
{{ "<twm_bol>"}}<br>
{{ "<identification_segment>"}}<br>
{{ "<registry_number>GLG0621</registry_number>"}}<br>
{{ "<date>01/09/2014</date>"}}<br>
{{ "<bol_reference>S320684664</bol_reference>"}}<br>
{{ "<customs_office_segment>"}}<br>
{{ "<code>01TG</code>"}}<br>
{{ "</customs_office_segment>"}}<br>
{{ "</identification_segment>"}}<br>
{{ "<bol_specific_segment>"}}<br>
{{ "<line_number>446</line_number>"}}<br>
{{ "<bol_nature>23</bol_nature>"}}<br>
{{ "<master_bol>"}}<br>
{{ "<customs_office_code>XXX</customs_office_code>"}}<br>
{{ "<registry_number>XXX</registry_number>"}}<br>
{{ "<date_of_departure/>"}}<br>
{{ "<master_bol_reference>XXX</master_bol_reference>"}}<br>
{{ "</master_bol>"}}<br>
{{ "<unique_carrier_reference>AGENT-BP000422</unique_carrier_reference>"}}<br>
{{ "<total_number_of_containers>4</total_number_of_containers>"}}<br>
{{ "<total_gross_mass_manifested>61200.00</total_gross_mass_manifested>"}}<br>
{{ "<volume_in_cubic_meters>136.00</volume_in_cubic_meters>"}}<br>
{{ "<bol_type_segment>"}}<br>
{{ "<code>BL</code>"}}<br>
{{ "</bol_type_segment>"}}<br>
{{ "<exporter_segment>"}}<br>
{{ "<code/>"}}<br>
{{ "<name>SHIPPER NAME AS PER BL</name>"}}<br>
{{ "<address>SHIPPER ADDRESS AS PER BL</address>"}}<br>
{{ "</exporter_segment>"}}<br>
{{ "<consignee_segment>"}}<br>
{{ "<code/>"}}<br>
{{ "<name>Cormart Nigeria Ltd</name>"}}<br>
{{ "<address>14 Chivita Avenue Ajao Estate - Apakun Oshodi Lagos, Nigeria</address>"}}<br>
{{ "</consignee_segment>"}}<br>
{{ "<notify_segment>"}}<br>
{{ "<code/>"}}<br>
{{ "<name>CORMART NIGERIA LIMITED</name>"}}<br>
{{ "<address>ILUPEJU INDUSTRIAL LAYOUT</address>"}}<br>
{{ "</notify_segment>"}}<br>
{{ "<place_of_loading>"}}<br>
{{ "<code>BEANR</code>"}}<br>
{{ "</place_of_loading>"}}<br>
{{ "<place_of_unloading>"}}<br>
{{ "<destport_code>NGLOS</destport_code>"}}<br>
{{ "<terminal_operator>"}}<br>
{{ "<terminalop_berthcode>AGENT-BP001845</terminalop_berthcode>"}}<br>
{{ "</terminal_operator>"}}<br>
</place_of_unloading>"}}<br>
{{ "<freight_segment>"}}<br>
{{ "<bol_freight_cost/>"}}<br>
{{ "<currency>USD</currency>"}}<br>
{{ "<indicator_segment/>"}}<br>
{{ "</freight_segment>"}}<br>
{{ "<packages_segment>"}}<br>
{{ "<package_type_code/>"}}<br>
{{ "<number_of_packages/>"}}<br>
{{ "<cargo_class_segment>"}}<br>
{{ "<cargo_code/>"}}<br>
{{ "<cargo_qty/>"}}<br>
{{ "<cargo_uom/>"}}<br>
{{ "<cargo_freight/>"}}<br>
{{ "</cargo_class_segment>"}}<br>
{{ "<shipping_marks/>"}}<br>
{{ "<goods_description>2400 BAGS NATROSOL 250 HHBR</goods_description>"}}<br>
{{ "</packages_segment>"}}<br>
{{ "<customs_segment>"}}<br>
{{ "<value/>"}}<br>
{{ "<currency/>"}}<br>
{{ "</customs_segment>"}}<br>
{{ "<transport_segment>"}}<br>
{{ "<value/>"}}<br>
{{ "<currency/>"}}<br>
{{ "</transport_segment>"}}<br>
{{ "<insurance_segment>"}}<br>
{{ "<value/>"}}<br>
{{ "<currency/>"}}<br>
{{ "</insurance_segment>"}}<br>
{{ "<seals_segment>"}}<br>
{{ "<number_of_seals>4</number_of_seals>"}}<br>
{{ "<mark_of_seals>031424</mark_of_seals>"}}<br>
{{ "<sealing_party_code>CR</sealing_party_code>"}}<br>
{{ "<information_part_a>Some information</information_part_a>"}}<br>
{{ "</seals_segment>"}}<br>
{{ "<operations_segment>"}}<br>
{{ "<location_segment>"}}<br>
{{ "<code>TG002</code>"}}<br>
{{ "<information/>"}}<br>
{{ "</location_segment>"}}<br>
{{ "</operations_segment>"}}<br>
{{ "<container>"}}<br>
{{ "<reference>ACLU2798901</reference>"}}<br>
{{ "<number>1</number>"}}<br>
{{ "<type>20GP</type>"}}<br>
{{ "<empty_full>1/1</empty_full>"}}<br>
{{ "<seals>031424</seals>"}}<br>
{{ "<mark1>PK</mark1>"}}<br>
{{ "<mark2/>"}}<br>
{{ "<sealing_party>CR</sealing_party>"}}<br>
{{ "<cargo_class_segment>"}}<br>
{{ "<cargo_code>DCBA20CL</cargo_code>"}}<br>
{{ "<cargo_freight/>"}}<br>
{{ "</cargo_class_segment>"}}<br>
{{ "</container>"}}<br>
{{ "<container>"}}<br>
{{ "<reference>DFSU2820609</reference>"}}<br>
{{ "<number/>"}}<br>
{{ "<type>20GP</type>"}}<br>
{{ "<empty_full>1/1</empty_full>"}}<br>
{{ "<seals>047731</seals>"}}<br>
{{ "<mark1>PK</mark1>"}}<br>
{{ "<mark2/>"}}<br>
{{ "<sealing_party>CR</sealing_party>"}}<br>
{{ "<cargo_class_segment>"}}<br>
{{ "<cargo_code>DCBA20CL</cargo_code>"}}<br>
{{ "<cargo_freight/>"}}<br>
{{ "</cargo_class_segment>"}}<br>
{{ "</container>"}}<br>
{{ "<container>"}}<br>
{{ "<reference>GCNU1193632</reference>"}}<br>
{{ "<number/>"}}<br>
{{ "<type>20GP</type>"}}<br>
{{ "<empty_full>1/1</empty_full>"}}<br>
{{ "<seals>048156</seals>"}}<br>
{{ "<mark1>PK</mark1>"}}<br>
{{ "<mark2/>"}}<br>
{{ "<sealing_party>CR</sealing_party>"}}<br>
{{ "<cargo_class_segment>"}}<br>
{{ "<cargo_code>DCBA20CL</cargo_code>"}}<br>
{{ "<cargo_freight/>"}}<br>
{{ "</cargo_class_segment>"}}<br>
{{ "</container>"}}<br>
{{ "<container>"}}<br>
{{ "<reference>SEGU3282170</reference>"}}<br>
{{ "<number/>"}}<br>
{{ "<type>20GP</type>"}}<br>
{{ "<empty_full>1/1</empty_full>"}}<br>
{{ "<seals>047753</seals>"}}<br>
{{ "<mark1>PK</mark1>"}}<br>
{{ "<mark2/>"}}<br>
{{ "<sealing_party>CR</sealing_party>"}}<br>
{{ "<cargo_class_segment>"}}<br>
{{ "<cargo_code>DCBA20CL</cargo_code>"}}<br>
{{ "<cargo_freight/>"}}<br>
{{ "</cargo_class_segment>"}}<br>
{{ "</container>"}}<br>
{{ "</bol_specific_segment>"}}<br>
{{ "</twm_bol>"}}<br>
